import Head from "next/head";
import Flow from "../components/flow/Flow";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ height: "100vh" }}>
        <Flow />
      </div>
    </div>
  );
}
